1st commit(Added Notification)(opening app from notification is in pr…
AkoG1/MovieApp pull request #5
Opened 2022-04-21 15:53 UTC by AkoG1

…ocess)

2022-05-02 16:38 UTC, chorobaev reviewed
Check carefully and fix it ASAP. If you have any problems, write in Slack.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +const val notificationId = "1"
Give a representative value for the const  `notificationId`. For example, `riminderNotificationIdExtra`.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +const val idExtra = ""
Why an empty string?

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +            .setVibrate(longArrayOf(1000, 1000, 1000))
Retrieve to constant fields.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/ui/datePickerDialog/ScheduleNotificationDialogFragment.kt
> +    private fun createNotification() {
Better to create notification channels in the `Application`'s `onCreate()` method. Read [this](https://stackoverflow.com/a/46348763/10452701). Do not forget to check android OS version. Should be O(26) or higher.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/ui/datePickerDialog/ScheduleNotificationDialogFragment.kt
> +        const val NAME = "MovieApp Channel"
Move this const too to the `Application` class.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/ui/movieDetails/MovieDetailsFragment.kt
> +                        binding.titleTV.text.toString(),
In case of error when retrieving details. Reminder with empty title can be scheduled. Handle this case. Check for emptiness.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/ui/movieDetails/MovieDetailsFragment.kt
> +            findNavController().navigate(action)
Navigate only if `Build.VERSION.SDK_INT > Build.VERSION_CODES.O`, because you are using `@RequiresApi(Build.VERSION_CODES.O)` in `ScheduleNotificationDialogFragment` or do not use the annotation. Instead handle both cases when SDK_INT is newer than O or lower than it in  `ScheduleNotificationDialogFragment.init()`.

2022-05-02 16:38 UTC, chorobaev commented on app/src/main/res/navigation/mobile_navigation.xml
> +        android:id="@+id/itemListDialogFragment"
Why its id is `itemListDialogFragment`. It is `ScheduleNotificationDialogFragment`. Do not forget to rename the action's name that navigates to this dialog.

2022-05-06 05:44 UTC, chorobaev requested changes

2022-05-06 05:44 UTC, chorobaev commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
What is this? Add to gitignore.

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/app/App.kt
> +            Toast.makeText(applicationContext, WARNING , Toast.LENGTH_SHORT).show()
It is not correct they will work as expected.

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/app/App.kt
> +        const val WARNING = "Notifications will not work on your device"
Remove this, everything that is visible to user should be saved in resources.

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/data/repository/MovieNetworkRepositoryImpl.kt
> +        runBlocking {
Redundant code. Remove!

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +const val reminderNotificationIdExtra = "1"
I meant the value "1" should be changed to something meaningful!

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +            .setVibrate(longArrayOf(VIBRATE_1_SEC, VIBRATE_1_SEC, VIBRATE_1_SEC))
It is not correct name. The main purpose of using constants is changing their values without changing their name. In this case if you change it to 2 seconds, you will change the name of the constant? Name it correctly, for example "VIBRATION_TIME_ONE", "VIBRATION_TIME_TWO" etc.

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/ui/movieDetails/MovieDetailsFragment.kt
> +                makeToastMessage(WARNING)
Use string resource!

2022-05-06 05:44 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/ui/movieDetails/MovieDetailsFragment.kt
> +            if (!title.isNullOrEmpty() && (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)) {
It will work above M not O, change it. Also changes in `ScheduleNotificationDialogFragment` needed. There `@RequiresApi(Build.VERSION_CODES.))` should be changed to "@RequiresApi(Build.VERSION_CODES.M)".

2022-05-06 05:45 UTC, chorobaev commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove the file and add to gitignore

2022-05-06 05:45 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/app/App.kt
> +            Toast.makeText(applicationContext, WARNING , Toast.LENGTH_SHORT).show()
Remove the else block

2022-05-06 12:35 UTC, AkoG1 commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +const val reminderNotificationIdExtra = "1"
what can it be :D

2022-05-10 06:33 UTC, chorobaev commented on app/src/main/java/com/example/movieapp/presentation/notifications/Notification.kt
> +const val reminderNotificationIdExtra = "1"
At least same as the variable name :)

2022-05-10 07:57 UTC, merged